### ISSUE TITLE
User Experience-New Feature: Add an Input Field/Button...

### ISSUE THREAD

**Issue by serge-fabiano** [LibusoftCicom/lc-datepicker#7]
Hi,
When I inserted the tag <lc-datepicker...> in my template, I would have expected an input field with the calendar button which is not the case.
When using your demo project, I just realized that I have to provide everything and interact with the visibility of your component via the property 'opened'.
It is a pain as I would have to create a component on my own that embeds this input field/button to not duplicate the code in every template.
is it possible to add this input field/button like in your demo project?
Thanks,
Serge.

**Comment by mematija** [comment]
Hi @LucasBrazi06 ,

wrapping the LCDatePicker in another component (with input, button etc.) is outside the scope of this project. We developed the picker component because didn't find another one that suited our need and opensourced it hoping it would help others as well. Internally, we are using it in combination other components of ours.

Feel free to wrap it yourself - the code from the the repo should be more than helpful (eg. /src/app/app.component).
